# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wejo1yAoRd1fzeUWVtHkVZP73ApjHDf8
"""

print("hello")

a=int(input("ENTER PRICE OF FIRST ITEM  "))
b=int(input("ENTER THE PRICE OF SECOND ITEM  "))
c=int(input("ENTER THE PRICE OF THIRD ITEM  "))
d=a+b+c
e=d*10/100
f=int(d)-int(e)
if (d>50):
  f=int(d)-int(e)
print(f)